### PR TITLE
Add webmaster sidebar email icon

### PR DESCRIPTION
**Pull request by wdconinc**

### CODE REVIEW

**Comment by buddhasystem** [comment]
Did you pick a good feather icon?

**Comment by buddhasystem** [comment]
It's work in progress, right?

**Comment by wdconinc** [comment]
Yeah, WIP. Alignment issues: 
image

**Comment by buddhasystem** [comment]
Doesn't look so bad... Geet doch!

**Comment by wdconinc** [comment]
This is better

image

**Pull request merged**
