### PR TITLE
fix: conferences 2022-2023 added

### LINKED ISSUE #47: Add conferences
i) Transversity 2022, Pavia, Italy on May 23-27, 2022 , https://agenda.infn.it/event/19219/
  1. EIC overview: Haiyan Gao(BNL): 

ii) Kick-Off Meeting - Synergies between the Electron-Ion Collider and the Large Hadron Collider, Jun 20 – 21, 2022, CERN; https://indico.ph.tum.de/event/7014/

  1.EIC Project Overview , Abhay Deshpande (Stonybrook )
  2.The EIC detector and R&D plans,   Silvia Dalla Torre (INFN)

iii) RHIC&AGS Annual Users Meeting 2022,  June 7-10, 2022, BNL, https://indico.bnl.gov/event/15479/ 

  1. EIC Project Status :  James Yeck ( BNL)
  2. Progress on EIC Accelerator: Michael Blaskiewicz (BNL)
  3. EIC Physics : Bernd Surrow (Temple University)
  4. EIC Detectors: John Lajoie (Iowa State University)

iv)  Diffraction and Low-x 2022,  24–30 Sept 2022, Corigliano Calabro, Italy,

   1. Detectors and physics at the Electron-Ion Collider: Charlotte Van Hulse (University of Alcalá de Henares)

On the Upcoming conferences, we can add:

i)  DIS2023:  March 27–31, 2023, East Lansing, Michigan, USA.,  https://indico.cern.ch/event/1199314/
ii) POETIC 2023: May 2-6, 2023, Sao Paulo, Brazil, https://www.ictp-saifr.org/poetic2023/
iii) SPIN2023, to be announced

### PR DESCRIPTION
**Pull request by wdconinc**
Closes #47

### CODE REVIEW

**Comment by wdconinc** [comment]
image

**Comment by wdconinc** [comment]
@buddhasystem Any reason why we cannot list `year` in the `upcoming` conference? When I do, they just disappear from the list. Logic in jekyll seems fine...

**Comment by buddhasystem** [comment]
Actually, the logic in the conference page is such that it doesn't feed the year value, for the upcoming conferences. Look at the invocation of the macro "conf_table", for the upcoming and for the past. The latter iterates over years, and the former does not. Let me know if I should change that, or whether you want to do it yourself. I guess the reason was pandemic-related and such that future conferences did not have a hard connection with the specific year. I think either variant makes sense.

**Comment by wdconinc** [comment]
It just seems like having to go through and add the year is counterintuitive. But I guess we can just document it in the conferences.yml.

**Comment by buddhasystem** [comment]
Do you mean back-filling the year? That would be OK. Why is it counterintuitive?

**Comment by wdconinc** [comment]
When entering a future conference with status `upcoming`, you cannot add the year because if you do it doesn't show up. When you move it to status `past` then you have to add the year. I wish we could just add the year right from the start and have everything be controlled only by the status.

**Pull request merged**
